"""update customer and remove company

Revision ID: 4151d0b3d400
Revises: 202605db4657
Create Date: 2026-09-25 09:42:09.404418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4151d0b3d400'
down_revision: Union[str, Sequence[str], None] = '202605db4657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_profile_id'), table_name='company_profile')
    op.drop_table('company_profile')
    op.add_column('customers', sa.Column('party', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('customer_initials', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(), server_default='Unknown', nullable=False))
    op.add_column('customers', sa.Column('ntn', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('gst', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('cnic', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('cust_relation', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('cust_priority', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('cust_type', sa.String(), server_default='Unknown', nullable=False))
    op.add_column('customers', sa.Column('cust_culture', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('payment_terms', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('tax_type', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('sales_rep_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('additional_details', sa.Text(), nullable=True))
    
    op.execute("UPDATE customers SET sector = 'Unknown' WHERE sector IS NULL")
    op.execute("UPDATE customers SET ho_address = 'Unknown' WHERE ho_address IS NULL")
    op.execute("UPDATE customers SET website = 'Unknown' WHERE website IS NULL")
    op.execute("UPDATE customers SET email = 'Unknown' WHERE email IS NULL")
    op.execute("UPDATE customers SET phone = 'Unknown' WHERE phone IS NULL")
    
    op.alter_column('customers', 'sector',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'ho_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('customers', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key('fk_customers_sales_rep_id_users', 'customers', 'users', ['sales_rep_id'], ['id'])
    op.drop_column('customers', 'inquiry_date')
    op.add_column('personnel', sa.Column('cp_name', sa.String(), server_default='Unknown', nullable=False))
    op.add_column('personnel', sa.Column('desg', sa.String(), nullable=True))
    op.drop_column('personnel', 'designation')
    op.drop_column('personnel', 'concerned_person')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personnel', sa.Column('concerned_person', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('personnel', sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('personnel', 'desg')
    op.drop_column('personnel', 'cp_name')
    op.add_column('customers', sa.Column('inquiry_date', sa.DATE(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_customers_sales_rep_id_users', 'customers', type_='foreignkey')
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'ho_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('customers', 'sector',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('customers', 'additional_details')
    op.drop_column('customers', 'sales_rep_id')
    op.drop_column('customers', 'tax_type')
    op.drop_column('customers', 'payment_terms')
    op.drop_column('customers', 'payment_method')
    op.drop_column('customers', 'cust_culture')
    op.drop_column('customers', 'cust_type')
    op.drop_column('customers', 'cust_priority')
    op.drop_column('customers', 'cust_relation')
    op.drop_column('customers', 'cnic')
    op.drop_column('customers', 'gst')
    op.drop_column('customers', 'ntn')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'customer_initials')
    op.drop_column('customers', 'party')
    op.create_table('company_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('company_profile_pkey'))
    )
    op.create_index(op.f('ix_company_profile_id'), 'company_profile', ['id'], unique=False)
    # ### end Alembic commands ###
